syntax = "proto3";

package nebius.vpc.v1;

import "buf/validate/validate.proto";
import "nebius/annotations.proto";
import "nebius/common/v1/metadata.proto";
import "nebius/common/v1/operation.proto";
import "nebius/vpc/v1/network.proto";

option go_package = "github.com/nebius/gosdk/proto/nebius/vpc/v1";
option java_multiple_files = true;
option java_outer_classname = "NetworkServiceProto";
option java_package = "ai.nebius.pub.vpc.v1";

// NetworkService provides operations for managing networks.
service NetworkService {
  option (api_service_name) = "vpc";

  // Retrieves a network by its ID.
  rpc Get(GetNetworkRequest) returns (Network);

  // Retrieves a network by its name within a specified parent.
  rpc GetByName(GetNetworkByNameRequest) returns (Network);

  // Lists networks within a specified parent.
  rpc List(ListNetworksRequest) returns (ListNetworksResponse);

  // Creates a new network with the specified configuration.
  rpc Create(CreateNetworkRequest) returns (common.v1.Operation);

  // Creates a default network, subnet, pools, and route table for a specified project.
  // Creates a default security group when that feature is enabled for the project.
  rpc CreateDefault(CreateDefaultNetworkRequest) returns (common.v1.Operation);

  // Updates an existing network with new configuration parameters.
  rpc Update(UpdateNetworkRequest) returns (common.v1.Operation);

  // Deletes a network by its ID.
  rpc Delete(DeleteNetworkRequest) returns (common.v1.Operation);
}

message GetNetworkRequest {
  // ID of the network.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcnetwork"]
    }
  ];
}

message GetNetworkByNameRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Name of the network.
  string name = 2 [(buf.validate.field).required = true];
}

message ListNetworksRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Maximum number of networks to return.
  int64 page_size = 2;

  // Token to retrieve the next page of networks.
  string page_token = 3;
}

message ListNetworksResponse {
  repeated Network items = 1;

  string next_page_token = 2;
}

message CreateNetworkRequest {
  // Metadata of the network.
  common.v1.ResourceMetadata metadata = 1 [
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
      required: true
    },
    (nid) = {
      parent_resource: ["project"]
    }
  ];

  // Specification of the network.
  NetworkSpec spec = 2;
}

message CreateDefaultNetworkRequest {
  // Metadata of the default network.
  common.v1.ResourceMetadata metadata = 1 [
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
      required: true
    },
    (nid) = {
      parent_resource: ["project"]
    }
  ];
}

message UpdateNetworkRequest {
  // Updated metadata of the network.
  common.v1.ResourceMetadata metadata = 1 [
    (nid) = {
      parent_resource: ["project"]
    },
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
    }
  ];

  // Updated specification of the network.
  NetworkSpec spec = 2;
}

message DeleteNetworkRequest {
  // ID of the network.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcnetwork"]
    }
  ];
}
