syntax = "proto3";

package nebius.vpc.v1;

import "buf/validate/validate.proto";
import "nebius/annotations.proto";
import "nebius/common/v1/metadata.proto";
import "nebius/common/v1/operation.proto";
import "nebius/vpc/v1/pool.proto";

option go_package = "github.com/nebius/gosdk/proto/nebius/vpc/v1";
option java_multiple_files = true;
option java_outer_classname = "PoolServiceProto";
option java_package = "ai.nebius.pub.vpc.v1";

// PoolService provides operations for managing pools.
service PoolService {
  option (api_service_name) = "vpc";

  // Retrieves a pool by its ID.
  rpc Get(GetPoolRequest) returns (Pool);

  // Retrieves a pool by its name within a specified parent.
  rpc GetByName(GetPoolByNameRequest) returns (Pool);

  // Lists pools within a specified parent.
  rpc List(ListPoolsRequest) returns (ListPoolsResponse);

  // Lists pools that use a specified pool as their source.
  rpc ListBySourcePool(ListPoolsBySourcePoolRequest) returns (ListPoolsResponse);

  // Creates a new pool with the specified configuration.
  rpc Create(CreatePoolRequest) returns (common.v1.Operation);

  // Updates an existing pool with new configuration parameters.
  rpc Update(UpdatePoolRequest) returns (common.v1.Operation);

  // Deletes a pool by its ID.
  rpc Delete(DeletePoolRequest) returns (common.v1.Operation);
}

message GetPoolRequest {
  // ID of the pool.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcpool"]
    }
  ];
}

message GetPoolByNameRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Name of the pool.
  string name = 2 [(buf.validate.field).required = true];
}

message ListPoolsRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Maximum number of pools to return.
  int64 page_size = 2;

  // Token to retrieve the next page of pools.
  string page_token = 3;
}

message ListPoolsBySourcePoolRequest {
  // ID of the source pool.
  string pool_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcpool"]
    }
  ];

  // Maximum number of pools to return.
  int64 page_size = 2;

  // Token to retrieve the next page of pools.
  string page_token = 3;
}

message ListPoolsResponse {
  repeated Pool items = 1;

  string next_page_token = 2;
}

message CreatePoolRequest {
  // Metadata of the pool.
  common.v1.ResourceMetadata metadata = 1 [
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
      required: true
    },
    (nid) = {
      parent_resource: ["project"]
    }
  ];

  // Specification of the pool.
  PoolSpec spec = 2 [(buf.validate.field).required = true];
}

message UpdatePoolRequest {
  // Updated metadata of the pool.
  common.v1.ResourceMetadata metadata = 1 [
    (nid) = {
      parent_resource: ["project"]
    },
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
    }
  ];

  // Updated specification of the pool.
  PoolSpec spec = 2;
}

message DeletePoolRequest {
  // ID of the pool.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcpool"]
    }
  ];
}
