syntax = "proto3";

package nebius.vpc.v1;

import "buf/validate/validate.proto";
import "nebius/annotations.proto";
import "nebius/common/v1/metadata.proto";
import "nebius/common/v1/operation.proto";
import "nebius/vpc/v1/route_table.proto";

option go_package = "github.com/nebius/gosdk/proto/nebius/vpc/v1";
option java_multiple_files = true;
option java_outer_classname = "RouteTableServiceProto";
option java_package = "ai.nebius.pub.vpc.v1";

// RouteTableService provides operations for managing route tables.
service RouteTableService {
  option (api_service_name) = "vpc";

  // Retrieves a route table by its ID.
  rpc Get(GetRouteTableRequest) returns (RouteTable);

  // Retrieves a route table by its name within a specified parent.
  rpc GetByName(GetRouteTableByNameRequest) returns (RouteTable);

  // Lists route tables within a specified parent.
  rpc List(ListRouteTablesRequest) returns (ListRouteTablesResponse);

  // Lists route tables that belong to a specified network.
  rpc ListByNetwork(ListRouteTablesByNetworkRequest) returns (ListRouteTablesResponse);

  // Creates a new route table with the specified configuration.
  rpc Create(CreateRouteTableRequest) returns (common.v1.Operation);

  // Updates an existing route table with new configuration parameters.
  rpc Update(UpdateRouteTableRequest) returns (common.v1.Operation);

  // Deletes a route table by its ID.
  rpc Delete(DeleteRouteTableRequest) returns (common.v1.Operation);
}

message GetRouteTableRequest {
  // ID of the route table.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcroutetable"]
    }
  ];
}

message GetRouteTableByNameRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Name of the route table.
  string name = 2 [(buf.validate.field).required = true];
}

message ListRouteTablesRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Maximum number of route tables to return.
  int64 page_size = 2;

  // Token to retrieve the next page of route tables.
  string page_token = 3;
}

message ListRouteTablesByNetworkRequest {
  // ID of the network.
  string network_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcnetwork"]
    }
  ];

  // Maximum number of route tables to return.
  int64 page_size = 2;

  // Token to retrieve the next page of route tables.
  string page_token = 3;
}

message ListRouteTablesResponse {
  repeated RouteTable items = 1;

  string next_page_token = 2;
}

message CreateRouteTableRequest {
  // Metadata of the route table.
  common.v1.ResourceMetadata metadata = 1 [
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
      required: true
    },
    (nid) = {
      parent_resource: ["project"]
    }
  ];

  // Specification of the route table.
  RouteTableSpec spec = 2 [(buf.validate.field).required = true];
}

message UpdateRouteTableRequest {
  // Updated metadata of the route table.
  common.v1.ResourceMetadata metadata = 1 [
    (nid) = {
      parent_resource: ["project"]
    },
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
    }
  ];

  // Updated specification of the route table.
  RouteTableSpec spec = 2;
}

message DeleteRouteTableRequest {
  // ID of the route table.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcroutetable"]
    }
  ];
}
