syntax = "proto3";

package nebius.vpc.v1;

import "buf/validate/validate.proto";
import "nebius/annotations.proto";
import "nebius/common/v1/metadata.proto";
import "nebius/common/v1/operation.proto";
import "nebius/vpc/v1/security_group.proto";

option go_package = "github.com/nebius/gosdk/proto/nebius/vpc/v1";
option java_multiple_files = true;
option java_outer_classname = "SecurityGroupServiceProto";
option java_package = "ai.nebius.pub.vpc.v1";

// SecurityGroupService provides operations for managing security groups.
service SecurityGroupService {
  option (api_service_name) = "vpc";

  // Retrieves a security group by its ID.
  rpc Get(GetSecurityGroupRequest) returns (SecurityGroup);

  // Retrieves a security group by its name within a specified parent.
  rpc GetByName(GetSecurityGroupByNameRequest) returns (SecurityGroup);

  // Lists security groups within a specified parent.
  rpc List(ListSecurityGroupsRequest) returns (ListSecurityGroupsResponse);

  // Lists security groups in a specified network.
  rpc ListByNetwork(ListSecurityGroupsByNetworkRequest) returns (ListSecurityGroupsResponse);

  // Creates a new security group with the specified configuration.
  rpc Create(CreateSecurityGroupRequest) returns (common.v1.Operation);

  // Updates an existing security group with new configuration parameters.
  rpc Update(UpdateSecurityGroupRequest) returns (common.v1.Operation);

  // Deletes a security group by its ID.
  rpc Delete(DeleteSecurityGroupRequest) returns (common.v1.Operation);
}

message GetSecurityGroupRequest {
  // ID of the security group.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcsecuritygroup"]
    }
  ];
}

message GetSecurityGroupByNameRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Name of the security group.
  string name = 2 [(buf.validate.field).required = true];
}

message ListSecurityGroupsRequest {
  // ID of the parent project.
  string parent_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["project"]
    }
  ];

  // Maximum number of security groups to return.
  int64 page_size = 2;

  // Token to retrieve the next page of security groups.
  string page_token = 3;
}

message ListSecurityGroupsByNetworkRequest {
  // ID of the network.
  string network_id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcnetwork"]
    }
  ];

  // Maximum number of security groups to return.
  int64 page_size = 2;

  // Token to retrieve the next page of security groups.
  string page_token = 3;
}

message ListSecurityGroupsResponse {
  repeated SecurityGroup items = 1;

  string next_page_token = 2;
}

message CreateSecurityGroupRequest {
  // Metadata of the security group.
  common.v1.ResourceMetadata metadata = 1 [
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
      required: true
    },
    (nid) = {
      parent_resource: ["project"]
    }
  ];

  // Specification of the security group.
  SecurityGroupSpec spec = 2 [(buf.validate.field).required = true];
}

message UpdateSecurityGroupRequest {
  // Updated metadata of the security group.
  common.v1.ResourceMetadata metadata = 1 [
    (nid) = {
      parent_resource: ["project"]
    },
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
    }
  ];

  // Updated specification of the security group.
  SecurityGroupSpec spec = 2;
}

message DeleteSecurityGroupRequest {
  // ID of the security group.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpcsecuritygroup"]
    }
  ];
}
