syntax = "proto3";

package nebius.vpc.v1;

import "buf/validate/validate.proto";
import "nebius/annotations.proto";
import "nebius/common/v1/metadata.proto";
import "nebius/common/v1/operation.proto";
import "nebius/vpc/v1/target_group.proto";

option go_package = "github.com/nebius/gosdk/proto/nebius/vpc/v1";
option java_multiple_files = true;
option java_outer_classname = "TargetGroupServiceProto";
option java_package = "ai.nebius.pub.vpc.v1";

// TargetGroupService provides operations for managing target groups.
service TargetGroupService {
  option (api_service_name) = "vpc";

  // Retrieves a target group by its ID.
  rpc Get(GetTargetGroupRequest) returns (TargetGroup);

  // Updates an existing target group with new configuration parameters.
  rpc Update(UpdateTargetGroupRequest) returns (common.v1.Operation);
}

message GetTargetGroupRequest {
  // ID of the target group.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["vpctargetgroup"]
    }
  ];
}

message UpdateTargetGroupRequest {
  // Updated metadata of the target group.
  common.v1.ResourceMetadata metadata = 1 [
    (nid) = {
      parent_resource: ["project"]
    },
    (buf.validate.field) = {
      cel: [
        {
          id: "metadata_name"
          message: "'name' must start with a letter or digit, allow '-', '_', '.', '/', and have a length between 2 and 255 characters."
          expression: "this.name.matches('^[a-zA-Z0-9][-_./a-zA-Z0-9]{1,254}$')"
        }
      ]
    }
  ];

  // Updated specification of the target group.
  TargetGroupSpec spec = 2;
}
