syntax = "proto3";

package nebius.ai.v1;

import "buf/validate/validate.proto";
import "nebius/annotations.proto";

option go_package = "github.com/nebius/gosdk/proto/nebius/ai/v1";
option java_multiple_files = true;
option java_outer_classname = "PricingProto";
option java_package = "ai.nebius.pub.ai.v1";

// PricingModelSpec defines how the workload's VM is priced.
// It mirrors the pricing model of the Compute Instance API.
message PricingModelSpec {
  oneof model {
    option (buf.validate.oneof).required = true;
    option (oneof_behavior) = IMMUTABLE;

    // A regular, non-preemptible VM.
    OnDemandSpec on_demand = 1 [
      (field_behavior) = MEANINGFUL_EMPTY_VALUE,
      (field_behavior) = IMMUTABLE
    ];

    // The preemptible VM accepts the current spot price.
    FollowsSpotPriceSpec follows_spot_price = 2 [
      (field_behavior) = MEANINGFUL_EMPTY_VALUE,
      (field_behavior) = IMMUTABLE
    ];

    // The preemptible VM accepts the current spot price unless it exceeds the maximum price specified by the selected
    // pricing policy. When the spot price exceeds that maximum price, the VM is preempted.
    SpotPricingPolicySpec spot_pricing_policy = 3 [(field_behavior) = IMMUTABLE];
  }
}

message OnDemandSpec {}

message FollowsSpotPriceSpec {}

message SpotPricingPolicySpec {
  // PricingPolicy ID used as the maximum agreed price for the preemptible VM.
  string id = 1 [
    (buf.validate.field).required = true,
    (nid) = {
      resource: ["pricingpolicy"]
    },
    (field_behavior) = IMMUTABLE
  ];
}
