name: CI
on:
  workflow_dispatch:
    inputs:
      debug_ssh:
        description: "Enable SSH debug with tmate, see https://github.com/marketplace/actions/debugging-with-tmate"
        required: false
        type: boolean
        default: false
  pull_request:
  push:
    branches:
      - main
      - sync/**
  schedule:
    - cron: "0 0 * * 1" # Each Monday

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: bufbuild/buf-action@fd21066df7214747548607aaa45548ba2b9bc1ff # v1.4.0
        with:
          setup_only: true
      - run: buf build --error-format github-actions
      - run: buf generate --error-format github-actions

  notify-slack-on-failure:
    name: Notify Slack on failure
    if: failure()
    needs: [buf]
    runs-on: ubuntu-latest
    steps:
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@03ea5433c137af7c0495bc0cad1af10403fc800c # v3.0.2
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_OAUTH_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL }}
            text: |
              🚨 Workflow *${{ github.workflow }}* failed on <${{ github.server_url }}/${{ github.repository }}|${{ github.repository }}>
              <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View run>
